=== chipvp/mlb-led-scoreboard/schemas/coordinates/w64h32.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "64x32 Scoreboard Coordinates",
  "x-indent": "  ",
  "type": "object",
  "required": ["format"],
  "properties": {
    "x-schema": {
      "type": "string",
      "default": "./../schemas/coordinates/w64h32.schema.json",
      "readOnly": true,
      "x-enforceConst": true,
      "x-hidden": true
    },
    "format":       { "$ref": "./_common.schema.json#/$defs/format" },
    "defaults":     { "$ref": "./_common.schema.json#/$defs/defaults" },
    "bases":        { "$ref": "./_common.schema.json#/$defs/bases" },
    "final":        { "$ref": "./_common.schema.json#/$defs/final" },
    "linescore":    { "$ref": "./_common.schema.json#/$defs/linescore" },
    "inning":       { "$ref": "./_common.schema.json#/$defs/inning" },
    "outs":         { "$ref": "./_common.schema.json#/$defs/outs" },
    "atbat":        { "$ref": "./_common.schema.json#/$defs/atbat" },
    "batter_count": { "$ref": "./_common.schema.json#/$defs/batter_count" },
    "nohitter":     { "$ref": "./_common.schema.json#/$defs/nohitter" },
    "pregame":      { "$ref": "./_common.schema.json#/$defs/pregame" },
    "standings":    { "$ref": "./_common.schema.json#/$defs/standings" },
    "status":       { "$ref": "./_common.schema.json#/$defs/status" },
    "teams":        { "$ref": "./_common.schema.json#/$defs/teams" },
    "news":         { "$ref": "./_common.schema.json#/$defs/news" },
    "plugins":      { "$ref": "./_common.schema.json#/$defs/plugins" },
    "network":      { "$ref": "./_common.schema.json#/$defs/network" }
  },
  "default": {
    "x-schema": "./../schemas/coordinates/w64h32.schema.json",
    "format": 9.0,
    "defaults": {
      "font_name": "4x6"
    },
    "bases": {
      "1B": { "x": 56, "y": 20, "size": 6 },
      "2B": { "x": 51, "y": 15, "size": 6 },
      "3B": { "x": 46, "y": 20, "size": 6 }
    },
    "final": {
      "inning":         { "x": 32, "y": 20 },
      "scrolling_text": { "x": 0,  "y": 31, "width": 64 },
      "nohit_text":     { "x": 1,  "y": 20 }
    },
    "linescore": {
      "enabled": true,
      "font_name": "tom-thumb",
      "innings": 9,
      "column_width": 5,
      "show_team": true,
      "team_abbrev_x": 1,
      "innings_start_x": 15,
      "background": {"x": 0, "y": 14, "width": 64, "height": 17},
      "away": {"y": 20},
      "home": {"y": 26}
    },
    "inning": {
      "break": {
        "number": { "x": 2, "y": 29 },
        "text":   { "x": 2, "y": 22 },
        "due_up": {
          "due":     { "x": 18, "y": 22 },
          "up":      { "x": 18, "y": 28 },
          "divider": { "draw": true, "x": 15, "y_start": 14, "y_end": 32 },
          "loop":    64,
          "leadoff": { "x": 32, "y": 20, "width": 32 },
          "on_deck": { "x": 32, "y": 26, "width": 32 },
          "in_hole": { "x": 32, "y": 32, "width": 32 }
        }
      },
      "number": {
        "x": 46, "y": 21,
        "nohit":        { "x": 46, "y": 20 },
        "perfect_game": { "x": 46, "y": 20 }
      },
      "arrow": {
        "size": 3,
        "up":   { "x_offset": -5, "y_offset": -4 },
        "down": { "x_offset": -5, "y_offset": -2 }
      }
    },
    "outs": {
      "1": { "x": 49, "y": 28, "size": 2 },
      "2": { "x": 53, "y": 28, "size": 2 },
      "3": { "x": 57, "y": 28, "size": 2 }
    },
    "atbat": {
      "batter":      { "x": 1,  "y": 29, "width": 20 },
      "pitcher":     { "x": 1,  "y": 21, "width": 24 },
      "pitch":       { "x": 1,  "y": 50, "enabled": false, "mph": false, "desc_length": "short" },
      "pitch_count": { "x": 1,  "y": 50, "enabled": false, "append_pitcher_name": false },
      "loop": 36,
      "strikeout":   { "x": 15, "y": 29, "font_name": "5x7", "desc_length": "short", "enabled": true },
      "play_result": { "x": 15, "y": 29, "font_name": "5x7", "desc_length": "short", "enabled": true }
    },
    "batter_count": {
      "x": 34, "y": 30,
      "nohit":        { "x": 34, "y": 32 },
      "perfect_game": { "x": 34, "y": 32 }
    },
    "nohitter": { "x": 34, "y": 26, "innings_until_display": 5 },
    "pregame": {
      "scrolling_text": { "x": 0, "y": 31, "width": 64, "warmup": { "x": 0, "y": 31, "width": 64 } },
      "start_time":     { "x": 32, "y": 20 },
      "warmup_text":    { "x": 32, "y": 20 }
    },
    "standings": {
      "offset": 6,
      "height": 30,
      "width":  64,
      "divider":    { "x": 13 },
      "stat_title": { "x": 28 },
      "team": {
        "name":       { "x": 1  },
        "record":     { "x": 31 },
        "games_back": { "x": 64 }
      },
      "postseason": {
        "matchup_y_gap": 6,
        "series_x_gap":  16,
        "wc_x_start":    2,
        "wc_y_start":    6,
        "ds_a_y_start":  25,
        "__comment":     "all other coords are based off wild card position"
      }
    },
    "status": {
      "text":           { "x": 32, "y": 20, "short_text": false },
      "scrolling_text": { "x": 0,  "y": 31, "width": 64 }
    },
    "teams": {
      "background": {
        "away": { "width": 64, "height": 7, "x": 0, "y": 0 },
        "home": { "width": 64, "height": 7, "x": 0, "y": 7 }
      },
      "name": {
        "away": { "x": 4, "y": 6  },
        "home": { "x": 4, "y": 13 },
        "full": true
      },
      "accent": {
        "away": { "width": 2, "height": 7, "x": 0, "y": 0 },
        "home": { "width": 2, "height": 7, "x": 0, "y": 7 }
      },
      "record": {
        "enabled":  false,
        "position": "absolute",
        "away": { "x": 15, "y": 6  },
        "home": { "x": 15, "y": 13 },
        "hide_record_on_high_line_score": true
      },
      "line_score": {
        "away": { "x": 62, "y": 6  },
        "home": { "x": 62, "y": 13 },
        "show_hits_and_errors": true,
        "show_abs_challenges":  true,
        "compress_digits": false,
        "shorten_team_name_on_high_line_score": true,
        "spacing": 3
      },
      "abs_challenges": {
        "away": { "x": 62, "size": 2, "squares": [1, 4]   },
        "home": { "x": 62, "size": 2, "squares": [8, 11] }
      }
    },
    "news": {
      "scrolling_text": { "x": 0,  "y": 30, "width": 64 },
      "time":           { "x": 40, "y": 8  },
      "conditions":     { "x": 40, "y": 16 },
      "temperature":    { "x": 10, "y": 23 },
      "wind_speed":     { "x": 0,  "y": -2 },
      "wind_dir":       { "x": 0,  "y": -2 },
      "wind":           { "x": 40, "y": 23 },
      "weather_icon":   { "x": 2,  "y": 1, "width": 15, "height": 15 }
    },
    "plugins": {},
    "network": {
      "font_name":  "4x6",
      "background": { "width": 7, "height": 7, "x": 57, "y": 25 },
      "text":       { "x": 61, "y": 31 }
    }
  }
}

=== chipvp/mlb-led-scoreboard/coordinates/w64h32.example.json
{
  "$schema": "./../schemas/coordinates/w64h32.schema.json",
  "format": 9.0,
  "defaults": {
    "font_name": "4x6"
  },
  "bases": {
    "1B": {
      "x": 56,
      "y": 20,
      "size": 6
    },
    "2B": {
      "x": 51,
      "y": 15,
      "size": 6
    },
    "3B": {
      "x": 46,
      "y": 20,
      "size": 6
    }
  },
  "final": {
    "inning": {
      "x": 32,
      "y": 20
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64
    },
    "nohit_text": {
      "x": 1,
      "y": 20
    }
  },
  "linescore": {
    "enabled": true,
    "font_name": "tom-thumb",
    "innings": 9,
    "column_width": 5,
    "show_team": true,
    "team_abbrev_x": 1,
    "innings_start_x": 15,
    "background": {
      "x": 0,
      "y": 14,
      "width": 64,
      "height": 17
    },
    "away": {
      "y": 20
    },
    "home": {
      "y": 26
    }
  },
  "inning": {
    "break": {
      "number": {
        "x": 2,
        "y": 29
      },
      "text": {
        "x": 2,
        "y": 22
      },
      "due_up": {
        "due": {
          "x": 18,
          "y": 22
        },
        "up": {
          "x": 18,
          "y": 28
        },
        "divider": {
          "draw": true,
          "x": 15,
          "y_start": 14,
          "y_end": 32
        },
        "loop": 64,
        "leadoff": {
          "x": 32,
          "y": 20,
          "width": 32
        },
        "on_deck": {
          "x": 32,
          "y": 26,
          "width": 32
        },
        "in_hole": {
          "x": 32,
          "y": 32,
          "width": 32
        }
      }
    },
    "number": {
      "x": 46,
      "y": 21,
      "nohit": {
        "x": 46,
        "y": 20
      },
      "perfect_game": {
        "x": 46,
        "y": 20
      }
    },
    "arrow": {
      "size": 3,
      "up": {
        "x_offset": -5,
        "y_offset": -4
      },
      "down": {
        "x_offset": -5,
        "y_offset": -2
      }
    }
  },
  "outs": {
    "1": {
      "x": 49,
      "y": 28,
      "size": 2
    },
    "2": {
      "x": 53,
      "y": 28,
      "size": 2
    },
    "3": {
      "x": 57,
      "y": 28,
      "size": 2
    }
  },
  "atbat": {
    "batter": {
      "x": 1,
      "y": 29,
      "width": 20
    },
    "pitcher": {
      "x": 1,
      "y": 21,
      "width": 24
    },
    "pitch": {
      "x": 1,
      "y": 50,
      "enabled": false,
      "mph": false,
      "desc_length": "short"
    },
    "pitch_count": {
      "x": 1,
      "y": 50,
      "enabled": false,
      "append_pitcher_name": false
    },
    "loop": 36,
    "strikeout": {
      "x": 15,
      "y": 29,
      "font_name": "5x7",
      "desc_length": "short",
      "enabled": true
    },
    "play_result": {
      "x": 15,
      "y": 29,
      "font_name": "5x7",
      "desc_length": "short",
      "enabled": true
    }
  },
  "batter_count": {
    "x": 34,
    "y": 30,
    "nohit": {
      "x": 34,
      "y": 32
    },
    "perfect_game": {
      "x": 34,
      "y": 32
    }
  },
  "nohitter": {
    "x": 34,
    "y": 26,
    "innings_until_display": 5
  },
  "pregame": {
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64,
      "warmup": {
        "x": 0,
        "y": 31,
        "width": 64
      }
    },
    "start_time": {
      "x": 32,
      "y": 20
    },
    "warmup_text": {
      "x": 32,
      "y": 20
    }
  },
  "standings": {
    "offset": 6,
    "height": 30,
    "width": 64,
    "divider": {
      "x": 13
    },
    "stat_title": {
      "x": 28
    },
    "team": {
      "name": {
        "x": 1
      },
      "record": {
        "x": 31
      },
      "games_back": {
        "x": 64
      }
    },
    "postseason": {
      "matchup_y_gap": 6,
      "series_x_gap": 16,
      "wc_x_start": 2,
      "wc_y_start": 6,
      "ds_a_y_start": 25,
      "__comment": "all other coords are based off wild card position"
    }
  },
  "status": {
    "text": {
      "x": 32,
      "y": 20,
      "short_text": false
    },
    "scrolling_text": {
      "x": 0,
      "y": 31,
      "width": 64
    }
  },
  "teams": {
    "background": {
      "away": {
        "width": 64,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 64,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "name": {
      "away": {
        "x": 4,
        "y": 6
      },
      "home": {
        "x": 4,
        "y": 13
      },
      "full": true
    },
    "accent": {
      "away": {
        "width": 2,
        "height": 7,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 2,
        "height": 7,
        "x": 0,
        "y": 7
      }
    },
    "record": {
      "enabled": false,
      "position": "absolute",
      "away": {
        "x": 15,
        "y": 6
      },
      "home": {
        "x": 15,
        "y": 13
      },
      "hide_record_on_high_line_score": true
    },
    "line_score": {
      "away": {
        "x": 62,
        "y": 6
      },
      "home": {
        "x": 62,
        "y": 13
      },
      "show_hits_and_errors": true,
      "show_abs_challenges": true,
      "compress_digits": false,
      "shorten_team_name_on_high_line_score": true,
      "spacing": 3
    },
    "abs_challenges": {
      "away": {
        "x": 62,
        "size": 2,
        "squares": [
          1,
          4
        ]
      },
      "home": {
        "x": 62,
        "size": 2,
        "squares": [
          8,
          11
        ]
      }
    }
  },
  "news": {
    "scrolling_text": {
      "x": 0,
      "y": 30,
      "width": 64
    },
    "time": {
      "x": 40,
      "y": 8
    },
    "conditions": {
      "x": 40,
      "y": 16
    },
    "temperature": {
      "x": 10,
      "y": 23
    },
    "wind_speed": {
      "x": 0,
      "y": -2
    },
    "wind_dir": {
      "x": 0,
      "y": -2
    },
    "wind": {
      "x": 40,
      "y": 23
    },
    "weather_icon": {
      "x": 2,
      "y": 1,
      "width": 15,
      "height": 15
    }
  },
  "plugins": {
    "clock": {
      "time": {
        "x": 32,
        "y": 19,
        "font_name": "9x15B"
      },
      "date": {
        "x": 32,
        "y": 28,
        "font_name": "4x6"
      }
    },
    "countdown": {
      "number": {
        "x": 32,
        "y": 15,
        "font_name": "9x15B"
      },
      "label": {
        "x": 32,
        "y": 23,
        "font_name": "4x6"
      },
      "event": {
        "x": 0,
        "y": 30,
        "width": 64,
        "font_name": "4x6"
      }
    }
  },
  "network": {
    "font_name": "4x6",
    "background": {
      "width": 7,
      "height": 7,
      "x": 57,
      "y": 25
    },
    "text": {
      "x": 61,
      "y": 31
    }
  }
}
